version: "3"

services: 
  app:
    build: .
    command: sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3500 -b 0.0.0.0"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - "4500:3500"
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      RAILS_ENV: development
      DB_USERNAME: webapp
      DB_PASSWORD: 123456
      DB_HOST: db
      DB_PORT: 43306
  db:
    image: mysql:8.0
    # for mac M1
    # platform: linux/amd64
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_USER: webapp
      MYSQL_DATABASE: webapp
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - '43306:3306'
    volumes:
      - /Users/chiendv/development/tcv_data:/var/lib/mysql
      - './docker/db/conf.d:/etc/mysql/conf.d'
volumes:
  db_data:
    driver: local
  bundle:
    driver: local
